spring:
  application:
    name: message-generation
  cloud:
    services:
      registrationMethod: route

eureka:
  client:
    preferIpAddress: true
  instance:
    hostname: ${CF_INSTANCE_INTERNAL_IP}
    nonSecurePort: ${PORT}

---

spring:
  profiles: dev

security:
  basic:
    enabled: false
